import type { NextPage } from "next";
import Head from "next/head";
import { CenteredForm } from "../components/CenteredElement";
import { ForgotPasswordForm } from "../components/CenteredElement/ForgotPasswordForm";

const ForgotPassword: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CenteredForm form={<ForgotPasswordForm />} />
    </>
  );
};

export default ForgotPassword;
