import type { NextPage } from "next";
import Head from "next/head";
import { CenteredForm } from "../components/CenteredElement";
import { RegisterForm } from "../components/CenteredElement/RegisterForm";

const Register: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CenteredForm form={<RegisterForm />} />
    </>
  );
};

export default Register;
